# Netlify configuration file

# Build settings
[build]
  # Directory to publish (relative to root)
  publish = "dist"
  # Command to run to build the site
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # SPA fallback
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow connections to the backend
    Access-Control-Allow-Origin = "*"

# Headers for API requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "no-store"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 